Add member to DB API
GoToGroMSP-20/GoToGroMSP-20-backend pull request #6
Opened 2022-09-21 15:08 UTC by Baavi

2022-09-22 01:37 UTC, ShiroKatake requested changes
This is good! I'm just a bit confused about the changes in the test file, but you just need to fix up the parameters for the route.

2022-09-22 01:37 UTC, ShiroKatake commented on routes/addMember.js
> +router.post("/addmember", async (_, res) => {
you need to take in `(req, res)` parameter not `(_,res)`

2022-09-22 01:37 UTC, ShiroKatake commented on routes/test.js
> -        data: result
did we need to modify this file?

2022-09-23 05:06 UTC, Baavi commented
Resolve issues

2022-09-23 07:35 UTC, ShiroKatake approved these changes
This looks good to merge! We don't need `db.end()` ln16 in addMember.js, but we can fix that in a new ticket. For now it won't work, but the logic looks fine so we should push this along

2022-09-23 08:44 UTC, merged